apiVersion: kustomize.config.k8s.io/v1beta1
namespace: mealie
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
#  - n8n-secret.yaml
#  - n8n-postgresql.yaml
