---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
stringData:
  # Recommended for n8n credential encryption (you can reference this via env later).
  # Use a long random string (>= 32 chars).
  N8N_ENCRYPTION_KEY: "bDymjAunmyazRsQGsQIlLavdpXLHXBQM"